const articles = [
	{
		id: 2,
		title: "Worlds Turned Upside Down",
		imgAlt: "Worlds Turned Upside Down",
		slug: "worlds-turned-upside-down-book",
		type: "Books",
		medium: 1,
		category: 2,
		price: {
			dollar:  20.58
		},
		description: "When the first season of Stranger Things debuted on Netflix in the summer of 2016, the show struck a nerve with millions of viewers worldwide and received broad critical acclaim. The series has gone on to win six Emmy Awards, but its success was driven more than anything by word of mouth, resonating across generations. Viewers feel personal connections to the characters. Now fans can immerse themselves in the world—or worlds—of Hawkins, Indiana, like never before.",
		url: "https://amzn.to/3nVRLEK",
		details: {
			"Dimensions": "7.33 x 1.08 x 10.26 inches",
			"Weight": "2.3 pounds",
			"Manufacturer": "Del Rey"
		},
		ratings: 4.8,
		gallery: [],
	},
	{
		id: 3,
		title: "Insulated Drinkware",
		imgAlt: "Insulated Drinkware",
		slug: "insulated-drinkware-kitchen",
		type: "Kitchen",
		medium: 1,
		category: 2,
		price: {
			dollar:  16.99
		},
		description: "Insulated drinkware delivers the ultimate combination of personality and performance for pure drinking enjoyment.",
		url: "https://amzn.to/39djBIc",
		details: {
			"Dimensions": "3.55 x 3.55 x 6.5 inches",
			"Weight": "7.5 ounces",
			"Manufacturer": "	Tervis Tumbler Company"
		},
		ratings: 4.7,
		gallery: [],
	},{
		id: 4,
		title: "Friends Don't Lie Pin",
		imgAlt: "Friends Don't Lie Pin",
		slug: "friends-dont-lie-pin-accessories",
		type: "Accessories",
		medium: 1,
		category: 2,
		price: {
			dollar:  11.46
		},
		description: "A cute pins with an exquisite and practical design, easy to match and make you catch other people's eyes.",
		url: "https://amzn.to/3620mPR",
		details: {
			"Dimensions": "4 x 3.25 x 0.65 inches",
			"Weight": "0.63 Ounces",
			"Manufacturer": "	Charmart"
		},
		ratings: 5,
		gallery: [],
	},{
		id: 5,
		title: "Eggo Card Game",
		imgAlt: "Eggo Card Game",
		slug: "eggo-card-game-games",
		type: "Games",
		medium: 1,
		category: 2,
		price: {
			dollar:  20.90
		},
		description: "Play as one of the characters from original Netflix series, Stranger Things in the Stranger Things Eggo Card Game! Play as Will, Mike, Lucas, Dustin, Eleven, Hopper or Barb!",
		url: "https://amzn.to/2UXSWa7",
		details: {
			"Dimensions": "2.52 x 9.25 x 4.13 inches",
			"Weight": "9.2 ounces",
			"Manufacturer": "	Charmart"
		},
		ratings: 4.5,
		gallery: [],
	},{
		id: 6,
		title: "Stranger Things Monopoly",
		imgAlt: "Stranger Things Monoply",
		slug: "stranger-things-monoply-games",
		type: "Games",
		medium: 1,
		category: 2,
		price: {
			dollar:  39.99
		},
		description: "Stranger Things theme Monopoly game, inspired by seasons 1-3 of the popular Netflix original series.",
		url: "https://amzn.to/3nXajo3",
		details: {
			"Dimensions": "3.19 x 13.11 x 10.51 inches",
			"Weight": "9.2 ounces",
			"Manufacturer": "	Charmart"
		},
		ratings: 4.5,
		gallery: [],
	},{
		id: 7,
		title: "Suspicious Minds: Stranger Things Novel",
		imgAlt: "Suspicious Minds: Stranger Things Novel",
		slug: "suspicious-minds-stranger-things-novel-books",
		type: "Books",
		medium: 1,
		category: 2,
		price: {
			dollar:  10.44
		},
		description: "It’s the summer of 1969, and the shock of conflict reverberates through the youth of America. As a student at a quiet college campus in the heartland of Indiana, Terry Ives couldn’t be farther from the front lines of Vietnam or the protests in Washington.",
		url: "https://amzn.to/3nUaiBi",
		details: {
			"Dimensions": "5.49 x 0.73 x 8.24 inches",
			"Weight": "9.6 ounces",
			"Manufacturer": "Del Rey"
		},
		ratings: 4.6,
		gallery: [],
	},{
		id: 8,
		title: "Hawkins Palace Arcade Vintage T-Shirt",
		imgAlt: "Hawkins Palace Arcade Vintage T-Shirt",
		slug: "hawkins-palace-arcade-vintage-t-shirt-clothes",
		type: "Clothes",
		medium: 1,
		category: 2,
		price: {
			dollar:  16.80
		},
		description: "Grab your skateboard, tube socks and some quarters to beat Mad Max at the high score in this awesome eighties tshirt. Its the perfect Christmas, graduation or birthday gift for any retro nostalgic tv show pop culture dungeons and dragons or overall comic con fan boy or girl.",
		url: "https://amzn.to/3nUaiBi",
		details: {
			"Dimensions": "10 x 7 x 1 inches",
			"Weight": "3.2 ounces",
			"Manufacturer": "Superluxe Clothing"
		},
		ratings: 4.7,
		gallery: [],
	},{
		id: 9,
		title: "Stranger Things Dungeons & Dragons",
		imgAlt: "Stranger Things Dungeons & Dragons",
		slug: "stranger-things-dungeons-dragons-games",
		type: "Games",
		medium: 1,
		category: 2,
		price: {
			dollar:  16.80
		},
		description: "The stranger things Dungeons & dragons starter set contains everything players need to embark on a stranger things adventure including the essential rules of the roleplaying game.",
		url: "https://amzn.to/3nThsWd",
		details: {
			"Dimensions": "2.01 x 9.02 x 11.5 inches",
			"Weight": "1.3 pounds",
			"Manufacturer": "Hasbro"
		},
		ratings: 4.7,
		gallery: [],
	},{
		id: 10,
		title: "Trivial Pursuit - Back to The 80s Edition",
		imgAlt: "Trivial Pursuit - Back to The 80s Edition",
		slug: "trivial-pursuit-back-to-the-80s-edition-games",
		type: "Games",
		medium: 1,
		category: 2,
		price: {
			dollar:  19.99
		},
		description: "How well do you know the 80s? Head back to a great decade in history and challenge friends with questions about the wild, wacky, totally tubular 1980s and all things Stranger Things! ",
		url: "https://amzn.to/3kYHeXr",
		details: {
			"Dimensions": "2.01 x 9.02 x 11.5 inches",
			"Weight": "1.3 pounds",
			"Manufacturer": "Hasbro"
		},
		ratings: 4.7,
		gallery: [],
	},{
		id: 11,
		title: "Lòrien Leaf Brooch",
		imgAlt: "Lòrien Leaf Brooch",
		slug: "lòrien-leaf-brooch-accessories",
		type: "Accessories",
		medium: 4,
		category: 1,
		price: {
			dollar:  43.1
		},
		description: "Original Reproduction of the Lòrien leaf brooch worn by the members of the Fellowship of the Ring.",
		url: "https://amzn.to/2WldHNz",
		details: {},
		ratings: 4.7,
		gallery: [],
	},{
		id: 12,
		title: "Stormtrooper pin",
		imgAlt: "Stormtrooper pin",
		slug: "stormtrooper-pin-accessories",
		type: "Accessories",
		medium: 5,
		category: 1,
		price: {
			dollar:  4.42
		},
		description: "A cute pins with an exquisite and practical design, easy to match and make you catch other people's eyes.",
		url: "https://amzn.to/2WldHNz",
		details: {},
		ratings: 4,
		gallery: [],
	},{
		id: 13,
		title: "The Babysitter T-Shirt",
		imgAlt: "The Babysitter T-Shirt",
		slug: "the-babysitter-t-shirt-clothes",
		type: "Clothes",
		medium: 1,
		category: 2,
		price: {
			dollar:  19.95
		},
		description: "A men t-shirt representing The Babysitter aka Steve Harrington from Stranger Things.",
		url: "https://amzn.to/3mtnhJ5",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 14,
		title: "Hawkins Middle School Hoodie",
		imgAlt: "Hawkins Middle School Hoodie",
		slug: "hawkins-middle-school-hoodie-clothes",
		type: "Clothes",
		medium: 1,
		category: 2,
		price: {
			dollar:  37.95
		},
		description: "Super soft and comfy Unisex Hawkins Middle School Hoodie.",
		url: "https://amzn.to/38eRcPU",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 15,
		title: "Lip Gloss Stranger Things",
		imgAlt: "Lip Gloss Stranger Things",
		slug: "lip-gloss-stranger-things-accessories",
		type: "Accessories",
		medium: 1,
		category: 2,
		price: {
			dollar:  10.99
		},
		description: "Glosses inspired by characters from Stranger Things. Flavors included: Vanilla, Cherry, Grape, Peach, Strawberry, & Apple.",
		url: "https://amzn.to/37ubHZY",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 16,
		title: "Max Crop Top",
		imgAlt: "Max Crop Top",
		slug: "max-crop-top-clothes",
		type: "Clothes",
		medium: 1,
		category: 2,
		price: {
			dollar:  5.99
		},
		description: "Max crop top for girls. Great with high waisted jeans or shorts.",
		url: "https://amzn.to/3gXxQTm",
		details: {},
		ratings: 4,
		gallery: [],
	},{
		id: 17,
		title: "Waffle Lip Balm",
		imgAlt: "Waffle Lip Balm",
		slug: "waffle-lip-balm-accessories",
		type: "Accessories",
		medium: 1,
		category: 2,
		price: {
			dollar:  6.99
		},
		description: "Waffle shaped lip balm flavored like Maple Syrup & Butter.",
		url: "https://amzn.to/3muMrGW",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 18,
		title: "Drawstring Backpack",
		imgAlt: "Drawstring Backpack",
		slug: "drawstring-backpack-accessories",
		type: "Accessories",
		medium: 1,
		category: 2,
		price: {
			dollar:  12.99
		},
		description: "Suitable for carrying items that aren't very heavy, like ipad, laptop and gym clothes.",
		url: "https://amzn.to/3mqgsI1",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 19,
		title: "Polaroid - Stranger Things Edition",
		imgAlt: "Polaroid - Stranger Things Edition",
		slug: "polaroid-stranger-things-edition-accessories",
		type: "Accessories",
		medium: 1,
		category: 2,
		price: {
			dollar:  151
		},
		description: "Limited edition: the Stranger Things edition OneStep2 is the perfect instant film camera for any superfan to capture all their stranger moment.",
		url: "https://amzn.to/3mwmyXk",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 20,
		title: "Dustin Cap - Tech Camp 85",
		imgAlt: "Dustin Cap - Tech Camp 85",
		slug: "dustin-cap-tech-camp-85-accessories",
		type: "Accessories",
		medium: 1,
		category: 2,
		price: {
			dollar:  13.99
		},
		description: "Fashion and vintage Tech Camp 85 cap similar to the one worn by Dustin the show.",
		url: "https://amzn.to/3msBN3M",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 21,
		title: "Puzzle - Double-Sided 200pc",
		imgAlt: "Puzzle - Double-Sided 200pc",
		slug: "puzzle-double-sided-200pc-games",
		type: "Games",
		medium: 1,
		category: 2,
		price: {
			dollar:  null
		},
		description: "Double-sided two scenes with one puzzle featuring favorite characters from the show.",
		url: "https://amzn.to/3h03jVc",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 22,
		title: "Palace Arcade Electronic Game",
		imgAlt: "Palace Arcade Electronic Game",
		slug: "palace-arcade-electronic-game-games",
		type: "Games",
		medium: 1,
		category: 2,
		price: {
			dollar:  26.99
		},
		description: "Awesome Stranger Things inspired arcade terminal. Blast back to the 80's with 20 games.",
		url: "https://amzn.to/3nA3Yza",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 23,
		title: "Stranger Things S02 - Collector's Edition",
		imgAlt: "Stranger Things S02 - Collector's Edition",
		slug: "stranger-things s02-collectors-edition-video",
		type: "Video",
		medium: 1,
		category: 2,
		price: {
			dollar:  68.34
		},
		description: "It's 1984 and the citizens of Hawkins, Indiana are still reeling from the horrors of the demagorgon and the secrets of Hawkins Lab. Will Byers has been rescued from the Upside Down but a bigger, sinister entity still threatens those who survived.",
		url: "https://amzn.to/34kqLXO",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 24,
		title: "Han Solo & Princess Leia Pins",
		imgAlt: "Han Solo & Princess Leia Pins",
		slug: "han-solo-&-princess-leia-pins-accessories",
		type: "Accessories",
		category: 1,
		medium: 5,
		price: {
			dollar:  15.99
		},
		description: "As Princess Leia confesses her love for Han Solo, Han simply replies by saying, 'I know.' Perfectly smug and genuine, this moment sets the precedence for their entire relationship. Both pins perfectly retell this Star Wars moment.",
		url: "https://amzn.to/3mB2qn4",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 25,
		title: "Star Wars Pin Set",
		imgAlt: "Star Wars Pin Set",
		slug: "star-wars-pin-set-accessories",
		type: "Accessories",
		category: 1,
		medium: 5,
		price: {
			dollar:  19.95
		},
		description: "Star Wars metal lapel pin set including R2-D2, C-3PO, Chewbacca and Jawa representations.",
		url: "https://amzn.to/3h8ljMX",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 26,
		title: "Star Wars Playing Cards Light Side Edition",
		imgAlt: "Star Wars Playing Cards Light Side Edition",
		slug: "star-wars-playing-cards-light-side-edition-games",
		type: "Games",
		category: 1,
		medium: 5,
		price: {
			dollar:  11.29
		},
		description: "Star Wars Playing Cards now in a new white colorway. Join Jedi Knights, climb aboard the Millennium Falcon, and become a Rebel or Resistance hero.",
		url: "https://amzn.to/3h2ke9D",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 27,
		title: "Baby Yoda - The Child Plush Toy",
		imgAlt: "Baby Yoda - The Child Plush Toy",
		slug: "baby-yoda-the-child-plush-toy-games",
		type: "Games",
		category: 1,
		medium: 5,
		price: {
			dollar:  33.98
		},
		description: "Inspired by the Disney+ series The Mandalorian, the adorable figure with green skin, big ears and large eyes resembles a baby Yoda but is referred to as The Child.",
		url: "https://amzn.to/3pmpFTR",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 28,
		title: "I Have Spoken Mug",
		imgAlt: "I Have Spoken Mug",
		slug: "i-have-spoken-mug-kitchen",
		type: "Kitchen",
		category: 1,
		medium: 5,
		price: {
			dollar:  21.99
		},
		description: "A 'the Mandalorian' inspired mug perfect for hot or cold beverages，made with durable material and a cool design.",
		url: "https://amzn.to/3mC6mUH",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 29,
		title: "Luke Skywalker Helmet",
		imgAlt: "Luke Skywalker Helmet",
		slug: "luke-skywalker-helmet-accessories",
		type: "Accessories",
		category: 1,
		medium: 5,
		price: {
			dollar:  253.59
		},
		description: "Premium electronic helmet: featuring highly-detailed deco, movie-inspired design, interior padding, lights, and sound FX, this full-scale replica of Luke skywalker's iconic helmet is a great addition to any fan's collection.",
		url: "https://amzn.to/3mBv0F1",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 30,
		title: "BB-8 App-Enabled Droid",
		imgAlt: "BB-8 Droid",
		slug: "bb-8-droid-games",
		type: "Games",
		category: 1,
		medium: 5,
		price: {
			dollar:  399.99
		},
		description: "Battle-Worn Exterior: BB-8 app-enabled Droid with a polycarbonate shell sports the wear and tear of Resistance missions. Bluetooth Smart connection allowing Gyroscopic propulsion to a 30m range.",
		url: "https://amzn.to/3h6c5kr",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 31,
		title: "R2-D2 App-Enabled Droid",
		imgAlt: "R2-D2 App-Enabled Droid",
		slug: "r2-d2-app-enabled-droid-games",
		type: "Games",
		category: 1,
		medium: 5,
		price: {
			dollar:  149.95
		},
		description: "Authentic Movement - Drive R2-D2 with your device, go from bipod to tripod stances, or trigger emotive waddles. Integrated Speaker & LEDs - Sounds come right from R2-D2, and front and rear lights are fully functional.",
		url: "https://amzn.to/2KEIIJZ",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 32,
		title: "Darth Vader T-Shirt",
		imgAlt: "Darth Vader T-Shirt",
		slug: "darth-vader-t-shirt-clothes",
		type: "Clothes",
		category: 1,
		medium: 5,
		price: {
			dollar:  13.60
		},
		description: "Darth Vader printed T-shirt, 100 percent cotton with short sleeves.",
		url: "https://amzn.to/2Wyb8rG",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 33,
		title: "Yoda Realistic Mask",
		imgAlt: "Yoda Realistic Mask",
		slug: "yoda-realistic-mask-accessories",
		type: "Accessories",
		category: 1,
		medium: 5,
		price: {
			dollar:  24.99
		},
		description: "Deluxe overhead latex master Yoda mask.",
		url: "https://amzn.to/3mBn8Dk",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 34,
		title: "R2-D2 Thermos",
		imgAlt: "R2-D2 Thermos",
		slug: "r2-d2-thermos-kitchen",
		type: "Kitchen",
		category: 1,
		medium: 5,
		price: {
			dollar:  14.99
		},
		description: "Thermos vacuum insulation technology for maximum temperature retention, not for use with hot liquids.",
		url: "https://amzn.to/3mBofD0",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 35,
		title: "Chewbacca Sounds Mask",
		imgAlt: "Chewbacca Sounds Mask",
		slug: "chewbacca-sounds-mask-accessories",
		type: "Accessories",
		category: 1,
		medium: 5,
		price: {
			dollar:  31.99
		},
		description: "This electronic mask is equipped with authentic Wookiee sound FX and activated by opening your mouth wide.",
		url: "https://amzn.to/37BZ1QC",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 36,
		title: "Jedi Fleece Bathrobe",
		imgAlt: "Jedi Fleece Bathrobe",
		slug: "jedi-fleece-bathrobe-clothes",
		type: "Clothes",
		category: 1,
		medium: 5,
		price: {
			dollar:  55.99
		},
		description: "Jedi Robe Yellow Bathrobe Adult Size",
		url: "https://amzn.to/2WwPEeH",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 37,
		title: "C-3PO Ink Pen",
		imgAlt: "C-3PO Ink Pen",
		slug: "c-3po-ink-pen-accessories",
		type: "Accessories",
		category: 1,
		medium: 5,
		price: {
			dollar:  18.95
		},
		description: "Metallic golden lacquer accented with a C-3PO emblem and satin-black appointments.",
		url: "https://amzn.to/37CJUqh",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 38,
		title: "Star Wars: Unlock! The Escape Game",
		imgAlt: "Star Wars: Unlock! The Escape Game",
		slug: "star-wars-unlock-the-escape-game-games",
		type: "Games",
		category: 1,
		medium: 5,
		price: {
			dollar:  34.99
		},
		description: "Live 3 epic escape adventures in the Star Wars universe! As rebels, smugglers, or imperial agents, search locations, combine items, use ships, weapons, interact with droids and machines in these three 60-minute adventures.",
		url: "https://amzn.to/2J9U20c",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 39,
		title: "Imperial Stormtrooper Voice Changer Helmet",
		imgAlt: "Imperial Stormtrooper Voice Changer Helmet",
		slug: "imperial-stormtrooper-voice-changer-helmet-accessories",
		type: "Accessories",
		category: 1,
		medium: 5,
		price: {
			dollar:  159.95,
		},
		description: "Collector-grade quality, part of the Black Series collection. Realistic detail and movie-accurate reproduction. Electronically change your voice to sound like an Imperial Stormtrooper.",
		url: "https://amzn.to/3r91x8G",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 40,
		title: "Han Solo in Carbonite Bottle Opener",
		imgAlt: "Han Solo in Carbonite Bottle Opener",
		slug: "han-solo-in-carbonite-bottle-opener-kitchen",
		type: "Kitchen",
		category: 1,
		medium: 5,
		price: {
			dollar: 10.00,
		},
		description: "Solid metal bottle opener. Recreates Han's frozen state from The Empire Strikes Back.",
		url: "https://amzn.to/3nDa7ul",
		details: {},
		ratings: 4,
		gallery: [],
	},{
		id: 41,
		title: "Darth Vader 2-Slice Toaster",
		imgAlt: "Darth Vader 2-Slice Toaster",
		slug: "darth-vader-2-slice-toaster-kitchen",
		type: "Kitchen",
		category: 1,
		medium: 5,
		price: {
			dollar: 34.99,
		},
		description: "Bring the dark lord into your kitchen - Vader's iconic chest plate in full color on the front of your toaster.",
		url: "https://amzn.to/3h5cLGy",
		details: {},
		ratings: 4,
		gallery: [],
	},{
		id: 42,
		title: "Master Yoda Bookend",
		imgAlt: "Master Yoda Bookend",
		slug: "master-yoda-bookend-accessories",
		type: "Accessories",
		category: 1,
		medium: 5,
		price: {
			dollar: 26.99,
		},
		description: "The L-Shaped bookend is both functional and decorative. It features a special angle that gives the illusion of books that are about to collapse, while Yoda behind it put out his hand to stop it.",
		url: "https://amzn.to/3h2Lzse",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 43,
		title: "The One Ring",
		imgAlt: "The One Ring",
		slug: "the-one-ring-accessories",
		type: "Accessories",
		category: 1,
		medium: 4,
		price: {
			dollar: 19.99,
		},
		description: "The One Ring replica of the Lord of The Rings.",
		url: "https://amzn.to/3nxmVCp",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 44,
		title: "Middle-Earth Map Blanket",
		imgAlt: "Middle-Earth Map Blanket",
		slug: "middle-earth-map-blanket-accessories",
		type: "Accessories",
		category: 1,
		medium: 4,
		price: {
			dollar: 32.99,
		},
		description: "The blanket is made of pilling-proof velvet, which is more comfortable And warm. Our blankets are made of the latest technical titles, which are lightweight,ultra soft and warm.",
		url: "https://amzn.to/34yBZbl",
		details: {},
		ratings: 4,
		gallery: [],
	},{
		id: 45,
		title: "You Shall Not Pass Carpet Entrance",
		imgAlt: "You Shall Not Pass Carpet Entrance",
		slug: "you-shall-not-pass-carpet-entrance-accessories",
		type: "Accessories",
		category: 1,
		medium: 4,
		price: {
			dollar: 32.99,
		},
		description: "With this doormat, you can do it like Gandalf: Keep the unwanted guests out.",
		url: "https://amzn.to/2KfExo5",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 46,
		title: "Bendable & Posable Dobby",
		imgAlt: "Bendable & Posable Dobby",
		slug: "bendable-&-posable-dobby-games",
		type: "Games",
		category: 1,
		medium: 7,
		price: {
			dollar: 12.99,
		},
		description: "Bend and pose Dobby into different positions!",
		url: "https://amzn.to/38pXeNS",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 47,
		title: "Dark Arts Collectible Set",
		imgAlt: "Dark Arts Collectible Set",
		slug: "dark-arts-collectible-set-accessories",
		type: "Accessories",
		category: 1, 
		medium: 7,
		price: {
			dollar: 35.96,
		},
		description: "Discover a replica of Tom Riddle's diary, decorative Death Eater mask, basilisk fang pen, and metallic-ink Dark Mark stickers in this deluxe set.",
		url: "https://amzn.to/3nz1uRr",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 48,
		title: "Tom Marvolo Riddle Diary",
		imgAlt: "Tom Marvolo Riddle Diary",
		slug: "tom-marvolo-riddle-diary-accessories",
		type: "Accessories",
		category: 1, 
		medium: 7,
		price: {
			dollar: 29.90,
		},
		description: "A replica of Tom Marvolo Riddle diary crafted in genuine leather.",
		url: "https://amzn.to/2KOaW4L",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 49,
		title: "Chocolate Frog Prop Replica",
		imgAlt: "Chocolate Frog Prop Replica",
		slug: "chocolate-frog-prop-replica-accessories",
		type: "Accessories",
		category: 1, 
		medium: 7,
		price: {
			dollar: 13.97,
		},
		description: "Includes a detailed keepsake box and a Dumbledore Famous Witches and Wizards Card.",
		url: "https://amzn.to/3paQ3jh",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 50,
		title: "Hermione's Time Turner",
		imgAlt: "Hermione's Time Turner",
		slug: "hermiones-time-turner-accessories",
		type: "Accessories",
		category: 1, 
		medium: 7,
		price: {
			dollar: 49.00,
		},
		description: "An authentic recreation of Hermione's time turner as featured in the movie Harry Potter and the Prisoner of Azkaban.",
		url: "https://amzn.to/3rjcGnq",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 51,
		title: "Cauldron Sculpted Mug",
		imgAlt: "Cauldron Sculpted Mug",
		slug: "cauldron-sculpted-mug-kitchen",
		type: "Kitchen",
		category: 1, 
		medium: 7,
		price: {
			dollar: 14.99,
		},
		description: "Harry Potter cauldron sculpted mug",
		url: "https://amzn.to/3pcxtap",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 52,
		title: "Gryffindor Scarf",
		imgAlt: "Gryffindor Scarf",
		slug: "gryffindor-scarf-clothes",
		type: "Clothes",
		category: 1, 
		medium: 7,
		price: {
			dollar: 34.95,
		},
		description: "Harry Potter Gryffindor scarf featuring a patch of the Gryffindor crest.",
		url: "https://amzn.to/2WBbMoc",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 53,
		title: "Platform 9 3/4 Phone Grip",
		imgAlt: "Platform 9 3/4 Phone Grip",
		slug: "platform-9-3-4-phone-grip-accessories",
		type: "Accessories",
		category: 1, 
		medium: 7,
		price: {
			dollar: 14.99,
		},
		description: "This Harry Potter styled grip offers a secure grip so you can text with one hand, snap better photos, and stop phone drops.",
		url: "https://amzn.to/2Km8tyW",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 54,
		title: "Harry Potter - UNO",
		imgAlt: "Harry Potter - UNO",
		slug: "harry-potter-uno-games",
		type: "Games",
		category: 1, 
		medium: 7,
		price: {
			dollar: 5.44,
		},
		description: "Now you can play UNO in the company of your favorite Harry Potter characters. Same gameplay as Basic UNO but features images of Hermione, Harry, Ron, and other characters from the magical world of Harry Potter",
		url: "https://amzn.to/3mFDISv",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 55,
		title: "Gringotts Bank Coin Collection",
		imgAlt: "Gringotts Bank Coin Collection",
		slug: "gringotts-bank-coin-collection-accessories",
		type: "Accessories",
		category: 1, 
		medium: 7,
		price: {
			dollar: 24.99,
		},
		description: "Each Galleon, Sickle and Knut is individually struck in rich detail and plated in either 24 karat gold, silver or copper.",
		url: "https://amzn.to/2KrWNup",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 56,
		title: "Gold Snitch Key Ring",
		imgAlt: "Gold Snitch Key Ring",
		slug: "gold-snitch-key-ring-accessories",
		type: "Accessories",
		category: 1, 
		medium: 7,
		price: {
			dollar: 10.40,
		},
		description: "Gold Snitch replica made as key ring.",
		url: "https://amzn.to/3ayeXoO",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 57,
		title: "Morphing Marauders Map Mug",
		imgAlt: "Morphing Marauders Map Mug",
		slug: "morphing-marauders-map-mug-kitchen",
		type: "Kitchen",
		category: 1, 
		medium: 7,
		price: {
			dollar: 29.99,
		},
		description: "Do you know Hogwarts as well as Moony, Wormtail, Padfoot and Prongs do? If you solemnly swear you are up to no good, then this 16 oz color changing mug is for you!",
		url: "https://amzn.to/2WGxBCI",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 58,
		title: "Wizard Chess Set",
		imgAlt: "Wizard Chess Set",
		slug: "wizard-chess-set-games",
		type: "Games",
		category: 1, 
		medium: 7,
		price: {
			dollar: 39.99,
		},
		description: "Bring the Wizarding World home to your family room with the officially licensed Harry Potter Wizard Chess Set.",
		url: "https://amzn.to/3roj6ld",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 59,
		title: "Hufflepuff Cup",
		imgAlt: "Hufflepuff Cup",
		slug: "hufflepuff-cup-accessories",
		type: "Accessories",
		category: 1, 
		medium: 7,
		price: {
			dollar: 69.11,
		},
		description: "A small replica of the Helga Hufflepuff cup.",
		url: "https://amzn.to/37GLyqU",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 60,
		title: "Hogwarts House Crest Pins",
		imgAlt: "Hogwarts House Crest Pins",
		slug: "hogwarts-house-crest pins-accessories",
		type: "Accessories",
		category: 1, 
		medium: 7,
		price: {
			dollar: 24.50,
		},
		description: "Finely detailed and hand enameled. Set includes all five pins.",
		url: "https://amzn.to/3pha33W",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 61,
		title: "Marauders Map Replica",
		imgAlt: "Marauders Map Replica",
		slug: "marauders-map-replica-accessories",
		type: "Accessories",
		category: 1, 
		medium: 7,
		price: {
			dollar: 29.50,
		},
		description: "A detailed full size Marauder's Map replica printed on parchment paper.",
		url: "https://amzn.to/3rnqaPh",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 62,
		title: "Harry Potter Circular Glasses",
		imgAlt: "Harry Potter Glasses",
		slug: "harry-potter-glasses-accessories",
		type: "Accessories",
		category: 1, 
		medium: 7,
		price: {
			dollar: 7.99,
		},
		description: "These circle glasses work well for Harry Potter costume.",
		url: "https://amzn.to/3nUXGdD",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 63,
		title: "Bertie Bott's Jelly Beans Candies",
		imgAlt: "Bertie Bott's Jelly Beans Candies",
		slug: "bertie-botts-jelly-beans-candies-food",
		type: "Food",
		category: 1, 
		medium: 7,
		price: {
			dollar: 17.67,
		},
		description: "The famours Bertie Bott's jelly beans.",
		url: "https://amzn.to/3mKKbeS",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 64,
		title: "Harry Wizard Wand",
		imgAlt: "Harry Wizard Wand",
		slug: "harry-wizard-wand-accessories",
		type: "Accessories",
		category: 1, 
		medium: 7,
		price: {
			dollar: 37.50,
		},
		description: "The Harry Potter Wand with Ollivanders Wand Box is a meticulous recreation of the wand and box props used in the Harry Potter film series, crafted with high quality materials.",
		url: "https://amzn.to/38slejl",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 65,
		title: "Felix Felicis Pendant",
		imgAlt: "Felix Felicis Pendant",
		slug: "felix-felicis-pendant-accessories",
		type: "Accessories",
		category: 1, 
		medium: 7,
		price: {
			dollar: 39.00,
		},
		description: "Potion bottle made of glass and metal adornments.",
		url: "https://amzn.to/3p9LW70",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 66,
		title: "Engraved Wooden Board Kitchen",
		imgAlt: "Engraved Wooden Board Kitchen",
		slug: "engraved-wooden-board-kitchen-kitchen",
		type: "Kitchen",
		category: 1, 
		medium: 4,
		price: {
			dollar: 29.95,
		},
		description: "Bamboo, laser engraved cutting board. The Ring represents power: power to control and influence things and other people.",
		url: "https://amzn.to/38vgFVt",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 67,
		title: "My Previous Mug",
		imgAlt: "My Previous Mug",
		slug: "my-previous-mug-kitchen",
		type: "Kitchen",
		category: 1, 
		medium: 4,
		price: {
			dollar: 14.99,
		},
		description: "Lightweight stainless steel campfire enamel mug.",
		url: "https://amzn.to/2WGF456",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 68,
		title: "Risk Board Game",
		imgAlt: "Risk Board Game",
		slug: "risk-boardgame-games",
		type: "Games",
		category: 1, 
		medium: 4,
		price: {
			dollar: 124.99,
		},
		description: "Step into the world of the Lord of the Rings with this special edition of Risk!",
		url: "https://amzn.to/3hfVH0A",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 69,
		title: "Hobbit Slippers",
		imgAlt: "Hobbit Slippers",
		slug: "hobbit-slippers-clothes",
		type: "Clothes",
		category: 1, 
		medium: 4,
		price: {
			dollar: 20.95,
		},
		description: "Plush slippers turn your footsies into furry adventure feet.",
		url: "https://amzn.to/3rvYk3t",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 70,
		title: "Gollum Plush",
		imgAlt: "Gollum Plush",
		slug: "gollum-plush-accessories",
		type: "Accessories",
		category: 1, 
		medium: 4,
		price: {
			dollar: 19.99,
		},
		description: "This cuddly Gollum Plush is made of high quality materials and is officially authorized by New Line Cinema.",
		url: "https://amzn.to/3mL6npo",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 71,
		title: "Arwen Evenstar Necklace",
		imgAlt: "Arwen Evenstar Necklace",
		slug: "arwen-evenstar-necklace-accessories",
		type: "Accessories",
		category: 1, 
		medium: 4,
		price: {
			dollar: 39.00,
		},
		description: "Delicate in appearance, suitable for any occasions and it makes you eye catching.",
		url: "https://amzn.to/3pnhQ07",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 72,
		title: "Wooden Music Box",
		imgAlt: "Wooden Music Box",
		slug: "wooden-music-box-accessories",
		type: "Accessories",
		category: 1, 
		medium: 4,
		price: {
			dollar: 21.99,
		},
		description: "Music boxes are a timeless treasure that can bring years of heartfelt pleasure to anyone.",
		url: "https://amzn.to/3mFI9wx",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 73,
		title: "Prancing Pony Mug",
		imgAlt: "Prancing Pony Mug",
		slug: "prancing-pony-mug-kitchen",
		type: "Kitchen",
		category: 1, 
		medium: 4,
		price: {
			dollar: 39.00,
		},
		description: "A Wooden Beer Mug make an ideal gift, whatever the occasion!",
		url: "https://amzn.to/3mDTy00",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 74,
		title: "The Prancing Pony Wooden Sign",
		imgAlt: "The Prancing Pony Wooden Sign",
		slug: "the-prancing-pony-wooden-sign-accessories",
		type: "Accessories",
		category: 1, 
		medium: 4,
		price: {
			dollar: 27.49,
		},
		description: "The sign is made from aluminum and printed with UV resistant inks for added durability, it can be used indoors or out.",
		url: "https://amzn.to/38qLNW6",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 75,
		title: "Bending Gollum Toy",
		imgAlt: "Bending Gollum Toy",
		slug: "bending-gollum-toy-games",
		type: "Games",
		category: 1, 
		medium: 4,
		price: {
			dollar: 13.97,
		},
		description: "Finely crafted collectible figures from Gollum.",
		url: "https://amzn.to/3hjDtvc",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 76,
		title: "4K Blu-ray Trilogy",
		imgAlt: "4K Blu-ray Trilogy",
		slug: "4k-blu-ray-trilogy-video",
		type: "Video",
		category: 1, 
		medium: 4,
		price: {
			dollar: 104.17,
		},
		description: "The Lord of the Rings theatrical and extended edition trilogy on stunning 4K ultra HD.",
		url: "https://amzn.to/38DiboE",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 77,
		title: "Bilbo Baggins Sting Sword",
		imgAlt: "Bilbo Baggins Sting Sword",
		slug: "bilbo-baggins-sting-sword-accessories",
		type: "Accessories",
		category: 1, 
		medium: 4,
		price: {
			dollar: 229.99,
		},
		description: "Exact replica of filming prop Bilbo Baggins Sting Sword.",
		url: "https://amzn.to/34NdOWR",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 78,
		title: "Hobbit-style Cloak",
		imgAlt: "Hobbit-style Cloak",
		slug: "hobbit-style-cloak-clothes",
		type: "Clothes",
		category: 1, 
		medium: 4,
		price: {
			dollar: 29.99,
		},
		description: "Cloak similar to the one wear by hobbits.",
		url: "https://amzn.to/2JrtJCU",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 79,
		title: "Drinks Coaster with Quotes",
		imgAlt: "Drinks Coaster with Quotes",
		slug: "drinks-coaster-with-quotes-kitchen",
		type: "Kitchen",
		category: 1, 
		medium: 4,
		price: {
			dollar: 29.99,
		},
		description: "Wooden drinks coasters set with engraved quotes from the Lord of the Rings.",
		url: "https://amzn.to/2WPwJvC",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 80,
		title: "The One Ring Mouse Pad",
		imgAlt: "The One Ring Mouse Pad",
		slug: "the-one-ring mouse-pad-accessories",
		type: "Accessories",
		category: 1, 
		medium: 4,
		price: {
			dollar: 7.90,
		},
		description: "A mouse pad with the elfvish inscription from The One Ring.",
		url: "https://amzn.to/3hli2Kq",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 81,
		title: "Journeys In Middle-Earth Board Game",
		imgAlt: "Journeys In Middle-Earth Board Game",
		slug: "journeys-in-middle-earth-board-game-games",
		type: "Games",
		category: 1, 
		medium: 4,
		price: {
			dollar: 79.96,
		},
		description: "A fully cooperative, app supported board game set in J.R.R; Tolkien’s iconic middle earth for 1 to 5 players.",
		url: "https://amzn.to/37Nr1AY",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 82,
		title: "Hoverboard 1/5 Scale Replica",
		imgAlt: "Hoverboard 1/5 Scale Replica",
		slug: "hoverboard-1-5-scale-replica-accessories",
		type: "Accessories",
		category: 1, 
		medium: 2,
		price: {
			dollar: 7.50,
		},
		description: "A 1/5 scale replica of the famous Hoverboard from Back to the Future.",
		url: "https://amzn.to/3aJMZGX",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 83,
		title: "Delorean Replica",
		imgAlt: "Delorean Replica",
		slug: "delorean-replica-accessories",
		type: "Accessories",
		category: 1, 
		medium: 2,
		price: {
			dollar: 39.90,
		},
		description: "Delorean Time Machine replica from Back to the Future.",
		url: "https://amzn.to/3rGQUKK",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 84,
		title: "Back in Time Board Game",
		imgAlt: "Back in Time Board Game",
		slug: "back-in-time-boardgame-games",
		type: "Games",
		category: 1, 
		medium: 2,
		price: {
			dollar: 24.47,
		},
		description: "Celebrate the 35th Anniversary of the groundbreaking franchise and join Marty McFly, Doc Brown and a time traveling DeLorean-fueled adventure of a lifetime!",
		url: "https://amzn.to/3rvUkj7",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 85,
		title: "Outatime License Plate",
		imgAlt: "Outatime License Plate",
		slug: "outatime-license-plate-accessories",
		type: "Accessories",
		category: 1, 
		medium: 2,
		price: {
			dollar: 20.00,
		},
		description: "Fake California license plate with OUTATIME inscriptions.",
		url: "https://amzn.to/34N5uGw",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 86,
		title: "Visual Book & 3D Poster",
		imgAlt: "Visual Book & 3D Poster",
		slug: "visual-book-3d-poster-books",
		type: "Books",
		category: 1, 
		medium: 2,
		price: {
			dollar: 295.00,
		},
		description: "Back to the Future: Sculpted Movie Poster & Back to the Future: The Ultimate Visual History Collector’s Edition is the collectible that fans have been waiting for!",
		url: "https://amzn.to/3ry5cgE",
		details: {},
		ratings: undefined,
		gallery: [],
	},{
		id: 87,
		title: "Hill Valley Cookbook",
		imgAlt: "Hill Valley Cookbook",
		slug: "hill-valley-cookbook-books",
		type: "Books",
		category: 1, 
		medium: 2,
		price: {
			dollar: 22.95,
		},
		description: "Travel through time and experience the gastronomic history of Hill Valley with this colorful cookbook inspired by the Back to the Future trilogy.",
		url: "https://amzn.to/3poH0LG",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 88,
		title: "Blu-ray BTTF Part II (VHS styled case)",
		imgAlt: "Blu-ray BTTF Part II (VHS styled case)",
		slug: "blu-ray-bttf-part-ii-vhs-styled-case-video",
		type: "Video",
		category: 1, 
		medium: 2,
		price: {
			dollar: 24.99,
		},
		description: "Relive the time travel adventure of a lifetime with Back to the Future - The Ultimate Collection in a special VHS case!",
		url: "https://amzn.to/3ry5DHO",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 89,
		title: "Marty McFly Action Figure",
		imgAlt: "Marty McFly Action Figure",
		slug: "marty-mcfly-action-figure-games",
		type: "Games",
		category: 1, 
		medium: 2,
		price: {
			dollar: 39.98,
		},
		description: "Standing approximately 7'' tall, the Ultimate Marty McFly is wearing the auto-adjusting jacket and self-lacing sneakers, and includes multiple heads and hands, with future soda and hoverboard accessories!",
		url: "https://amzn.to/3rA1XFA",
		details: {},
		ratings: 0,
		gallery: [],
	},{
		id: 90,
		title: "Doc Brown Planter",
		imgAlt: "Doc Brown Planter",
		slug: "doc-brown-planter-accessories",
		type: "Accessories",
		category: 1, 
		medium: 2,
		price: {
			dollar: 27.99,
		},
		description: "A unique pottery planter with Doc Brown face, convenient plastic drip tray and chia seed packets for 3 plantings.",
		url: "https://amzn.to/3rEqJEz",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 91,
		title: "Marty McFly Cap",
		imgAlt: "Marty McFly Cap",
		slug: "marty-mcfly-cap-clothes",
		type: "Clothes",
		category: 1, 
		medium: 2,
		price: {
			dollar: 24.99,
		},
		description: "Re-creates the futuristic baseball cap worn by Marty McFly during his visit to 2015 in Back to the Future Part II",
		url: "https://amzn.to/3puiau6",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 92,
		title: "Marty MacFly Casio Watch",
		imgAlt: "Marty MacFly Casio Watch",
		slug: "marty-macfly-casio watch-accessories",
		type: "Accessories",
		category: 1, 
		medium: 2,
		price: {
			dollar: 24.95,
		},
		description: "8-Digit Calculator; Constants for addition, subtraction, multiplication and division.",
		url: "https://amzn.to/3ry3iwf",
		details: {},
		ratings: 0,
		gallery: [],
	},{
		id: 93,
		title: "50 Pieces Stickers Set",
		imgAlt: "50 Pieces Stickers Set",
		slug: "50-pieces-stickers-set-accessories",
		type: "Accessories",
		category: 1, 
		medium: 2,
		price: {
			dollar: 6.99,
		},
		description: "A Back to the Future set of 50 stickers.",
		url: "https://amzn.to/3pqRASn",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 94,
		title: "DeLorean Pin",
		imgAlt: "DeLorean Pin",
		slug: "delorean-pin-accessories",
		type: "Accessories",
		category: 1, 
		medium: 2,
		price: {
			dollar: 10.00,
		},
		description: "DeLorean shaped pin from Back to the Future.",
		url: "https://amzn.to/3nS1kVz",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 95,
		title: "DeLorean Time Machine Tie",
		imgAlt: "DeLorean Time Machine Tie",
		slug: "delorean-time-machine-tie-clothes",
		type: "Clothes",
		category: 1, 
		medium: 2,
		price: {
			dollar: 22.95,
		},
		description: "Microfiber necktie, crafted by hand with DeLorean time machine patterns.",
		url: "https://amzn.to/3mTi5hM",
		details: {},
		ratings: 22.95,
		gallery: [],
	},{
		id: 96,
		title: "Air Mag Keychain",
		imgAlt: "Air Mag Keychain",
		slug: "air-mag-keychain-accessories",
		type: "Accessories",
		category: 1, 
		medium: 2,
		price: {
			dollar: 1,
		},
		description: "Back to the Future keychain",
		url: "https://amzn.to/3aN1fyK",
		details: {},
		ratings: 0,
		gallery: [],
	},{
		id: 97,
		title: "Capacitor LED Kit",
		imgAlt: "Capacitor LED Kit",
		slug: "capacitor-led-kit-games",
		type: "Games",
		category: 1, 
		medium: 2,
		price: {
			dollar: 36.77,
		},
		description: "Back to the Future capacitor Kit with LED light.",
		url: "https://amzn.to/2Mcf5Ao",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 98,
		title: "Central Perk Wireless Phone Charger",
		imgAlt: "Central Perk Wireless Phone Charger",
		slug: "central-perk-wireless-phone-charger-accessories",
		type: "Accessories",
		category: 2, 
		medium: 2,
		price: {
			dollar: 49.99,
		},
		description: "Friends wireless phone charger: Embrace the convenience of a wireless charger throughout the day with no more switching of cables and your tech will be fully charged when you head home from work.",
		url: "https://amzn.to/3puLYXi",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 99,
		title: "4 Mini Glasses with Quotes",
		imgAlt: "4 Mini Glasses with Quotes",
		slug: "4-mini-glasses-with-quotes-kitchen",
		type: "Kitchen",
		category: 2, 
		medium: 2,
		price: {
			dollar: 21.20,
		},
		description: "Mini glass set: this 4-pack of mini glasses features some of the most memorable quotes from the hit TV show Friends so you replay your favorite scenes with your pals.",
		url: "https://amzn.to/3nZyrH1",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 100,
		title: "Central Perk Travel Coffee Mug",
		imgAlt: "Central Perk Travel Coffee Mug",
		slug: "central-perk-travel-coffee-mug-kitchen",
		type: "Kitchen",
		category: 2, 
		medium: 2,
		price: {
			dollar: 12.99,
		},
		description: "Friends mug: Reminisce on your favorite TV show with this Friends commuter mug! Designed with the hilarious Friends comedy in mind, this mug is sure to make any fan of the series smile.",
		url: "https://amzn.to/34TVZFx",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 101,
		title: "Friends Keychain",
		imgAlt: "Friends Keychain",
		slug: "friends-keychain-accessories",
		type: "Accessories",
		category: 2, 
		medium: 2,
		price: {
			dollar: 9.99,
		},
		description: "Merchandise inspired by Friends, the keychain is perfect gift for your best friend, boy friend, girl friend especially friends fans!",
		url: "https://amzn.to/3rw8ukm",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 102,
		title: "Caramel Scented Candle",
		imgAlt: "Caramel Scented Candle",
		slug: "caramel-scented-candle-accessories",
		type: "Accessories",
		category: 2, 
		medium: 2,
		price: {
			dollar: 9.99,
		},
		description: "Sit back and reminisce about your favourite episode of Friends as you evoke the ambiance of Central Perk by lighting this caramel toffee scented candle",
		url: "https://amzn.to/37Xd2bV",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 103,
		title: "Central Perk Fluffy Slippers",
		imgAlt: "Central Perk Fluffy Slippers",
		slug: "central-perk-fluffy-slippers",
		type: "Clothes",
		category: 2, 
		medium: 2,
		price: {
			dollar: 25.13,
		},
		description: "Perfect for any fan of the famous TV series, these shoes will be sure to keep you warm and cosy.",
		url: "https://amzn.to/3o2b7bx",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 104,
		title: "Coaster Set",
		imgAlt: "Coaster Set",
		slug: "coaster-set-kitchen",
		type: "Kitchen",
		category: 2, 
		medium: 2,
		price: {
			dollar: 15.77,
		},
		description: "Coasters are inspired from Friends Tv Show.",
		url: "https://amzn.to/3aQONOl",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 105,
		title: "How You Doin' T-Shirt",
		imgAlt: "How You Doin' T-Shirt",
		slug: "how-you-doin-t-shirt-clothes",
		type: "Clothes",
		category: 2, 
		medium: 2,
		price: {
			dollar: 7.99,
		},
		description: "Black t-Shirt with printed quote from Joey",
		url: "https://amzn.to/2L4DaZq",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 106,
		title: "You Are My Lobster: Bath Fizzers",
		imgAlt: "You Are My Lobster: Bath Fizzers",
		slug: "you-are-my-lobster-bath-fizzers-bathroom",
		type: "Bathroom",
		category: 2, 
		medium: 2,
		price: {
			dollar: 0,
		},
		description: "Reminisce on your favourite scenes from Friends as you enjoy a fizzy bath with the You Are My Lobster Bath Fizzers. Shaped like a pair of lobsters, they’re the perfect item for any fan.",
		url: "https://amzn.to/3aOqi4o",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 107,
		title: "I'll Be There For You Cosmetic Bag",
		imgAlt: "I'll Be There For You Cosmetic Bag",
		slug: "I-ll-be-there-for-you-cosmetic-bag-bathroom",
		type: "Bathroom",
		category: 2, 
		medium: 2,
		price: {
			dollar: 14.97,
		},
		description: "A Friends inspired bag to get your cosmetics anywhere you go.",
		url: "https://amzn.to/2MlhybX",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 108,
		title: "Peephole Mug with Coaster & Spoon",
		imgAlt: "Peephole Mug with Coaster & Spoon",
		slug: "peephole-mug-with-coaster-spoon-kitchen",
		type: "Kitchen",
		category: 2, 
		medium: 2,
		price: {
			dollar: 18.97,
		},
		description: "Simple yet stylish cup suitable as a gift for your friends and relatives.",
		url: "https://amzn.to/34TfbmQ",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 109,
		title: "Quizz Cards",
		imgAlt: "Quizz Cards",
		slug: "quizz-cards-games",
		type: "Games",
		category: 2, 
		medium: 2,
		price: {
			dollar: 9.99,
		},
		description: "Test your friends and family on their knowledge of the popular TV show, Friends, with this Friends trivia quiz game!",
		url: "https://amzn.to/3hqTwHO",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 110,
		title: "Questions Cards",
		imgAlt: "Questions Cards",
		slug: "questions-cards-games",
		type: "Games",
		category: 2, 
		medium: 2,
		price: {
			dollar: 9.97,
		},
		description: "Test your friends and family on their knowledge of the popular TV show, Friends, with this Friends Trivia Quiz Game!",
		url: "https://amzn.to/2L3EonA",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 111,
		title: "Peephole Door Frame",
		imgAlt: "Peephole Door Frame",
		slug: "peephole-door-frame-accessories",
		type: "Accessories",
		category: 2, 
		medium: 2,
		price: {
			dollar: 13.95,
		},
		description: "A yellow peephole frame similar to the one in the serie.",
		url: "https://amzn.to/2L1ysM3",
		details: {},
		ratings: 4,
		gallery: [],
	},{
		id: 112,
		title: "Peehole Keychain",
		imgAlt: "Peehole Keychain",
		slug: "peehole-keychain-accessories",
		type: "Accessories",
		category: 2, 
		medium: 2,
		price: {
			dollar: 14.44,
		},
		description: "There's nothing quite so iconic as the Monica's Door Frame in Friends. Keep it always with you with this keychain.",
		url: "https://amzn.to/2L1KhSg",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 113,
		title: "Turkey Bath Fizzers",
		imgAlt: "Turkey Bath Fizzers",
		slug: "turkey-bath-fizzers-bathroom",
		type: "Bathroom",
		category: 2, 
		medium: 2,
		price: {
			dollar: 10.99,
		},
		description: "Delight fans of Friends the Television Series with a pair of bath fizzers that reference the episode where Joey recalls him and Monica having turkeys on their heads.",
		url: "https://amzn.to/3ht1Kzd",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 114,
		title: "Unagi Coffee Mug",
		imgAlt: "Unagi Coffee Mug",
		slug: "unagi-coffee-mug-kitchen",
		type: "Kitchen",
		category: 2, 
		medium: 2,
		price: {
			dollar: 14.99,
		},
		description: "Reminisce on your favorite TV show with this Friends Unagi mug! Designed with the hilarious Friends comedy in mind, this mug is sure to make any fan of the series smile.",
		url: "https://amzn.to/3aT7VLM",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 115,
		title: "Hand Balm Collection",
		imgAlt: "Hand Balm Collection",
		slug: "hand-balm-collection-bathroom",
		type: "Bathroom",
		category: 2, 
		medium: 2,
		price: {
			dollar: 14.99,
		},
		description: "Moisturising balm: Delight fans of Friends with a set of 3 hand balms, each bottle featuring an icon from the show including Ross’s sofa, the Central Perk sign, and a taxi.",
		url: "https://amzn.to/3hy8fAL",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 116,
		title: "Bath Advent Calendar",
		imgAlt: "Bath Advent Calendar",
		slug: "bath-advent-calendar-bathroom",
		type: "Bathroom",
		category: 2, 
		medium: 2,
		price: {
			dollar: 29.99,
		},
		description: "Christmas calendar: the run-up to Christmas has never been more exciting and what better way to celebrate than with the Friends Central Perk 12 Days of Bath and Body Advent Calendar.",
		url: "https://amzn.to/2L8NnUM",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 117,
		title: "Central Perk Tableware",
		imgAlt: "Central Perk Tableware",
		slug: "central-perk-tableware-kitchen",
		type: "Kitchen",
		category: 2, 
		medium: 2,
		price: {
			dollar: 19.99,
		},
		description: "Getting together with Friends has never been easier thanks to this 60-piece tableware set that features the iconic hangout spot from the hit TV show, Central Perk.",
		url: "https://amzn.to/3nZch7M",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 117,
		title: "Game of Thrones Monopoly",
		imgAlt: "Game of Thrones Monopoly",
		slug: "game-of-thrones-monopoly-games",
		type: "Games",
		category: 2, 
		medium: 3,
		price: {
			dollar: 70.00,
		},
		description: "Based on the hit TV series from HBO: Game of Thrones fans can travel the legendary lands of Westeros as you buy, sell, and trade locations from the seven Kingdoms in this edition of the Monopoly game",
		url: "https://amzn.to/3hAKGaH",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 118,
		title: "Game of Thrones Risk",
		imgAlt: "Game of Thrones Risk",
		slug: "game-of-thrones-risk",
		type: "Games",
		category: 2, 
		medium: 3,
		price: {
			dollar: 86.20,
		},
		description: "Claim your right to the Iron Throne with one of seven Noble House armies. Each army is composed of 45 finely crafted game pieces (315 game pieces total) represented by two different sculpted designs (1 unit army and 3 unit army) and one sculpted Seat of Power (castle).",
		url: "https://amzn.to/3o88h4X",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 119,
		title: "Playing Cards",
		imgAlt: "Playing Cards",
		slug: "playing-cards-games",
		type: "Games",
		category: 2, 
		medium: 3,
		price: {
			dollar: 12.99,
		},
		description: "As the last season of game of Thrones nears, reflect on the faces we've grown to know and admire... Or despise.",
		url: "https://amzn.to/3b1wlmq",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 120,
		title: "Sword Throne Mug",
		imgAlt: "Sword Throne Mug",
		slug: "sword-throne-mug-kitchen",
		type: "Kitchen",
		category: 2, 
		medium: 3,
		price: {
			dollar: 27.99,
		},
		description: "",
		url: "https://amzn.to/383czVs",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 121,
		title: "Engraved Wood Cutting Board",
		imgAlt: "Engraved Wood Cutting Board",
		slug: "engraved-wood-cutting-board-kitchen",
		type: "Kitchen",
		category: 2, 
		medium: 3,
		price: {
			dollar: 38.99,
		},
		description: "Beautiful, durable bamboo cutting board with 'Dinner is Coming' engraving.",
		url: "https://amzn.to/3hxRHcf",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 122,
		title: "Dragon Eggs Candles",
		imgAlt: "Dragon Eggs Candles",
		slug: "dragon-eggs-candles-accessories",
		type: "Accessories",
		category: 2, 
		medium: 3,
		price: {
			dollar: 24.95,
		},
		description: "Dragon eggs are coming. High-quality and long-lasting burning candles. Comes with a ready to be gifted box.",
		url: "https://amzn.to/38PZgHf",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 123,
		title: "Seven Kingdoms Glass",
		imgAlt: "Seven Kingdoms Glass",
		slug: "seven-kingdoms-glass-kitchen",
		type: "Kitchen",
		category: 2, 
		medium: 3,
		price: {
			dollar: 44.99,
		},
		description: "Take a step into Westeros with this Game of Thrones glass!",
		url: "https://amzn.to/383Fs3N",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 124,
		title: "Hand of The King Brooch",
		imgAlt: "Hand of The King Brooch",
		slug: "hand-of-the-king-brooch-pin-accessories",
		type: "Accessories",
		category: 2, 
		medium: 3,
		price: {
			dollar: 4.95,
		},
		description: "Inspired by Game of Thrones Hand of The King Pin Brooch",
		url: "https://amzn.to/353PXlT",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 125,
		title: "Iron Throne Replica",
		imgAlt: "Iron Throne Replica",
		slug: "iron-throne-replica-accessories",
		type: "Accessories",
		category: 2, 
		medium: 3,
		price: {
			dollar: 58.78,
		},
		description: "Based on HBO's award-winning television series Game of Thrones. Here is a fantastic mini version of the Iron Throne replica.",
		url: "https://amzn.to/3pHqtTa",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 126,
		title: "Hodor Door Stop",
		imgAlt: "Hodor Door Stop",
		slug: "hodor-door-stop-accessories",
		type: "Accessories",
		category: 2, 
		medium: 3,
		price: {
			dollar: 9.95,
		},
		description: "Not all superheroes wear capes, some just hold the door.",
		url: "https://amzn.to/3827Ljg",
		details: {},
		ratings: 4,
		gallery: [],
	},{
		id: 127,
		title: "Arya Stark Action Figure",
		imgAlt: "Arya Stark Action Figure",
		slug: "arya-stark-action-figure-games",
		type: "Games",
		category: 2, 
		medium: 3,
		price: {
			dollar: 14.84,
		},
		description: "Incredibly detailed figure of Arya Stark modeled from digitalscans of actress Maisie Williams.",
		url: "Incredibly detailed figure of Arya Stark modeled from digitalscans of actress Maisie Williams",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 128,
		title: "Longclaw Letter Opener",
		imgAlt: "Longclaw Letter Opener",
		slug: "longclaw-letter-opener-accessories",
		type: "Accessories",
		category: 2, 
		medium: 3,
		price: {
			dollar: 22.50,
		},
		description: "Diecast metal handle and stainless steel blade.",
		url: "https://amzn.to/3pCRlUv",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 129,
		title: "Stark Shield Pendant",
		imgAlt: "Stark Shield Pendant",
		slug: "stark-shield-pendant-accessories",
		type: "Accessories",
		category: 2, 
		medium: 3,
		price: {
			dollar: 31.16,
		},
		description: "Available from Noble Collection is the Game of Thrones Stark Shield Die-Cast Pendant Necklace. This officially licensed and detailed metal necklace would make the perfect gift for any fan of the books or TV Series.",
		url: "https://amzn.to/3o6uUqv",
		details: {},
		ratings: 4,
		gallery: [],
	},{
		id: 130,
		title: "Winterfell 3D Puzzle",
		imgAlt: "Winterfell 3D Puzzle",
		slug: "winterfell-3d-puzzle-games",
		type: "Games",
		category: 2, 
		medium: 3,
		price: {
			dollar: 49.95,
		},
		description: "As solid and foreboding as the North itself, Winterfell stands proud as the ancestral home of House Stark.",
		url: "https://amzn.to/38PK3WJ",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 131,
		title: "Fuzzy Blanket",
		imgAlt: "Fuzzy Blanket",
		slug: "fuzzy-blanket-accessories",
		type: "Accessories",
		category: 2, 
		medium: 3,
		price: {
			dollar: 29.99,
		},
		description: "Get cozy and warm with this extremely luxurious soft and fluffy plush blanket, perfect for snuggling up on the couch, bed, chilly movie theater, park or perfect personal gift for any occasion.",
		url: "https://amzn.to/3pJJlRo",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 132,
		title: "The Complete Seasons 1-8 (Blu-ray)",
		imgAlt: "The Complete Seasons 1-8 (Blu-ray)",
		slug: "the-complete-seasons-1-8-blu-ray-video",
		type: "Video",
		category: 2, 
		medium: 3,
		price: {
			dollar: 219.95,
		},
		description: "This limited-edition, custom-designed complete collector’s set includes all 73 episodes of this epic eight season series. Also included is 15 hours of bonus content and never-before-seen footage.",
		url: "https://amzn.to/3rLlO4B",
		details: {},
		ratings: 5,
		gallery: [],
	},{
		id: 133,
		title: "House Stark Banner",
		imgAlt: "House Stark Banner",
		slug: "house-stark-banner-accessories",
		type: "Accessories",
		category: 2, 
		medium: 3,
		price: {
			dollar: 4.5,
		},
		description: "Ever Wondered What It Would Be Like To Live In Westeros? Find Out With This Lifesize Game Of Thrones Wall Banner!",
		url: "https://amzn.to/3pKGWWX",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 134,
		title: "Dinner is Coming Apron",
		imgAlt: "Dinner is Coming Apron",
		slug: "dinner-is-coming-apron-kitchen",
		type: "Kitchen",
		category: 2, 
		medium: 3,
		price: {
			dollar: 29.99,
		},
		description: "This 100% cotton apron and mitt is cool, stylish and attention grabbing and makes the perfect gift for yourself or any fan of Game of Thrones.",
		url: "https://amzn.to/386Vt9j",
		details: {},
		ratings: 4.5,
		gallery: [],
	},{
		id: 135,
		title: "Hold The Door Doormat",
		imgAlt: "Hold The Door Doormat",
		slug: "hold-the-door-doormat-accessories",
		type: "Accessories",
		category: 2, 
		medium: 3,
		price: {
			dollar: 24.88,
		},
		description: "",
		url: "https://amzn.to/3hHACwA",
		details: {},
		ratings: 3.5,
		gallery: [],
	},{
		id: 136,
		title: "Bathroom Basket Tank",
		imgAlt: "Bathroom Basket Tank",
		slug: "bathroom-basket-tank-bathroom",
		type: "Bathroom",
		category: 2, 
		medium: 3,
		price: {
			dollar: 17.99,
		},
		description: "",
		url: "https://amzn.to/3n80nHe",
		details: {},
		ratings: 4.5,
		gallery: [],
	}
];

export default articles;
