const articles = [
	{
		id: 2,
		title: "Stranger Things: Worlds Turned Upside Down",
		imgAlt: "Stranger Things: Worlds Turned Upside Down",
		type: "Books",
		medium: 1,
		category: 2,
		price: "$20.58",
		description: "When the first season of Stranger Things debuted on Netflix in the summer of 2016, the show struck a nerve with millions of viewers worldwide and received broad critical acclaim. The series has gone on to win six Emmy Awards, but its success was driven more than anything by word of mouth, resonating across generations. Viewers feel personal connections to the characters. Now fans can immerse themselves in the world—or worlds—of Hawkins, Indiana, like never before.",
		url: "https://amzn.to/3nVRLEK",
		details: {
			"Dimensions": "7.33 x 1.08 x 10.26 inches",
			"Weight": "2.3 pounds",
			"Manufacturer": "Del Rey"
		},
		ratings: 4.8,
		gallery: [],
	},
	{
		id: 3,
		title: "Stranger Things - Insulated Drinkware",
		imgAlt: "Stranger Things - Insulated Drinkware",
		type: "Kitchen & Dining",
		medium: 1,
		category: 2,
		price: "$16.99",
		description: "Insulated drinkware delivers the ultimate combination of personality and performance for pure drinking enjoyment.",
		url: "https://amzn.to/39djBIc",
		details: {
			"Dimensions": "3.55 x 3.55 x 6.5 inches",
			"Weight": "7.5 ounces",
			"Manufacturer": "	Tervis Tumbler Company"
		},
		ratings: 4.7,
		gallery: [],
	},{
		id: 4,
		title: "Friends Don't Lie Pins",
		imgAlt: "Friends Don't Lie Pins",
		type: "Accessories",
		medium: 1,
		category: 2,
		price: "$11.46",
		description: "A cute pins with an exquisite and practical design, easy to match and make you catch other people's eyes.",
		url: "https://amzn.to/3620mPR",
		details: {
			"Dimensions": "4 x 3.25 x 0.65 inches",
			"Weight": "0.63 Ounces",
			"Manufacturer": "	Charmart"
		},
		ratings: 5,
		gallery: [],
	},{
		id: 5,
		title: "Eggo Card Game",
		imgAlt: "Eggo Card Game",
		type: "Games",
		medium: 1,
		category: 2,
		price: "$20.90",
		description: "Play as one of the characters from original Netflix series, Stranger Things in the Stranger Things Eggo Card Game! Play as Will, Mike, Lucas, Dustin, Eleven, Hopper or Barb!",
		url: "https://amzn.to/2UXSWa7",
		details: {
			"Dimensions": "2.52 x 9.25 x 4.13 inches",
			"Weight": "9.2 ounces",
			"Manufacturer": "	Charmart"
		},
		ratings: 4.5,
		gallery: [],
	},{
		id: 6,
		title: "Stranger Things Monopoly",
		imgAlt: "Stranger Things Monoply",
		type: "Games",
		medium: 1,
		category: 2,
		price: "$39.99",
		description: "Stranger Things theme Monopoly game, inspired by seasons 1-3 of the popular Netflix original series.",
		url: "https://amzn.to/3nXajo3",
		details: {
			"Dimensions": "3.19 x 13.11 x 10.51 inches",
			"Weight": "9.2 ounces",
			"Manufacturer": "	Charmart"
		},
		ratings: 4.5,
		gallery: [],
	},{
		id: 7,
		title: "Suspicious Minds: Stranger Things Novel",
		imgAlt: "Suspicious Minds: Stranger Things Novel",
		type: "Books",
		medium: 1,
		category: 2,
		price: "$10.44",
		description: "It’s the summer of 1969, and the shock of conflict reverberates through the youth of America. As a student at a quiet college campus in the heartland of Indiana, Terry Ives couldn’t be farther from the front lines of Vietnam or the protests in Washington.",
		url: "https://amzn.to/3nUaiBi",
		details: {
			"Dimensions": "5.49 x 0.73 x 8.24 inches",
			"Weight": "9.6 ounces",
			"Manufacturer": "Del Rey"
		},
		ratings: 4.6,
		gallery: [],
	},{
		id: 8,
		title: "Hawkins Palace Arcade Vintage T-Shirt",
		imgAlt: "Hawkins Palace Arcade Vintage T-Shirt",
		type: "Clothes",
		medium: 1,
		category: 2,
		price: "$16.80",
		description: "Grab your skateboard, tube socks and some quarters to beat Mad Max at the high score in this awesome eighties tshirt. Its the perfect Christmas, graduation or birthday gift for any retro nostalgic tv show pop culture dungeons and dragons or overall comic con fan boy or girl.",
		url: "https://amzn.to/3nUaiBi",
		details: {
			"Dimensions": "10 x 7 x 1 inches",
			"Weight": "3.2 ounces",
			"Manufacturer": "Superluxe Clothing"
		},
		ratings: 4.7,
		gallery: [],
	},{
		id: 9,
		title: "Stranger Things Dungeons & Dragons",
		imgAlt: "Stranger Things Dungeons & Dragons",
		type: "Games",
		medium: 1,
		category: 2,
		price: "$16.80",
		description: "The stranger things Dungeons & dragons starter set contains everything players need to embark on a stranger things adventure including the essential rules of the roleplaying game.",
		url: "https://amzn.to/3nThsWd",
		details: {
			"Dimensions": "2.01 x 9.02 x 11.5 inches",
			"Weight": "1.3 pounds",
			"Manufacturer": "Hasbro"
		},
		ratings: 4.7,
		gallery: [],
	},{
		id: 10,
		title: "Trivial Pursuit - Back to The 80s Edition",
		imgAlt: "Trivial Pursuit - Back to The 80s Edition",
		type: "Games",
		medium: 1,
		category: 2,
		price: "$19.99",
		description: "How well do you know the 80s? Head back to a great decade in history and challenge friends with questions about the wild, wacky, totally tubular 1980s and all things Stranger Things! ",
		url: "https://amzn.to/3kYHeXr",
		details: {
			"Dimensions": "2.01 x 9.02 x 11.5 inches",
			"Weight": "1.3 pounds",
			"Manufacturer": "Hasbro"
		},
		ratings: 4.7,
		gallery: [],
	},{
		id: 11,
		title: "Lòrien Leaf Brooch",
		imgAlt: "Lòrien Leaf Brooch",
		type: "Accessories",
		medium: 4,
		category: 1,
		price: "$43.1",
		description: "Original Reproduction of the Lòrien leaf brooch worn by the members of the Fellowship of the Ring.",
		url: "https://amzn.to/2WldHNz",
		details: {},
		ratings: 4.7,
		gallery: [],
	},{
		id: 12,
		title: "Stormtrooper pin",
		imgAlt: "Stormtrooper pin",
		type: "Accessories",
		medium: 5,
		category: 1,
		price: "$4.42",
		description: "A cute pins with an exquisite and practical design, easy to match and make you catch other people's eyes.",
		url: "https://amzn.to/2WldHNz",
		details: {},
		ratings: 4,
		gallery: [],
	}
];

export default articles;
