const items = [
	{
		id: 1,
		title: "Pins Denver",
		coverSrc: "/images/covers/denver.jpg",
		coverAlt: "Denver Cover",
		imgSrc: "/images/articles/denver00001.jpg",
		imgAlt: "Denver, the Last Dinosaur - Pins",
		color: "white",
		category: "Pins",
		medium: 1,
		price: "11,90 €",
		description: "A colorfull pins of Denver eye-winking face.",
		url: "",
		details: {
			"Size": "33cm",
			"Weight": "33g",
		},
		gallery: [
			{ alt: "Stranger Things", src: "/images/covers/stranger-things.jpg" },
			{ alt: "Stranger Things", src: "/images/covers/stranger-things.jpg" },
			{ alt: "Stranger Things", src: "/images/covers/stranger-things.jpg" },
			{ alt: "Stranger Things", src: "/images/covers/stranger-things.jpg" }
		],
	},
	{
		id: 2,
		title: "Stranger Things - Dans l'envers du décor",
		coverSrc: "/images/covers/stranger-things.jpg",
		coverAlt: "Stranger Things Cover",
		imgSrc: "/images/articles/stranger-things00001/main.jpg",
		imgAlt: "Stranger Things - Dans l'envers du décor",
		color: "#ff002e",
		category: "Books",
		medium: 1,
		price: "27,19 €",
		description: "A colorfull pins of Denver eye-winking face.",
		url: "",
		details: {
			"Size": "33cm",
			"Weight": "33g",
		},
		gallery: [
			{ alt: "Stranger Things", src: "/images/articles/stranger-things00001/gallery/01.jpg" },
			{ alt: "Stranger Things", src: "/images/articles/stranger-things00001/gallery/02.jpg" },
			{ alt: "Stranger Things", src: "/images/articles/stranger-things00001/gallery/03.jpg" },
			{ alt: "Stranger Things", src: "/images/articles/stranger-things00001/gallery/04.jpg" },
		],
	},
	{
		id: 3,
		title: "Pins Denver",
		imgSrc: "/images/articles/denver00001.jpg",
		imgAlt: "Denver, the Last Dinosaur - Pins",
		color: "white",
		category: "Pins",
		medium: 2,
		price: "11,90 €",
		description: "A colorfull pins of Denver eye-winking face.",
		url: "",
		details: {
			"Size": "33cm",
			"Weight": "33g",
		},
		gallery: [
			{ alt: "Stranger Things", src: "/images/covers/stranger-things.jpg" },
			{ alt: "Stranger Things", src: "/images/covers/stranger-things.jpg" },
			{ alt: "Stranger Things", src: "/images/covers/stranger-things.jpg" },
			{ alt: "Stranger Things", src: "/images/covers/stranger-things.jpg" },
		],
	},
	{
		id: 4,
		title: "Pins Denver",
		imgSrc: "/images/articles/denver00001.jpg",
		imgAlt: "Denver, the Last Dinosaur - Pins",
		color: "white",
		category: "Pins",
		medium: 2,
		price: "11,90 €",
		description: "A colorfull pins of Denver eye-winking face.",
		url: "",
		details: {
			"Size": "33cm",
			"Weight": "33g",
		},
		gallery: [
			{ alt: "Stranger Things", src: "/images/covers/stranger-things.jpg" },
			{ alt: "Stranger Things", src: "/images/covers/stranger-things.jpg" },
			{ alt: "Stranger Things", src: "/images/covers/stranger-things.jpg" },
			{ alt: "Stranger Things", src: "/images/covers/stranger-things.jpg" },
		],
	},
	{
		id: 5,
		title: "Pins Denver",
		imgSrc: "/images/articles/denver00001.jpg",
		imgAlt: "Denver, the Last Dinosaur - Pins",
		color: "white",
		category: "Pins",
		medium: 2,
		price: "11,90 €",
		description: "A colorfull pins of Denver eye-winking face.",
		url: "",
		details: {
			"Size": "33cm",
			"Weight": "33g",
		},
		gallery: [
			{ alt: "Stranger Things", src: "/images/covers/stranger-things.jpg" },
			{ alt: "Stranger Things", src: "/images/covers/stranger-things.jpg" },
			{ alt: "Stranger Things", src: "/images/covers/stranger-things.jpg" },
			{ alt: "Stranger Things", src: "/images/covers/stranger-things.jpg" },
		],
	},
	{
		id: 6,
		title: "Pins Denver",
		imgSrc: "/images/articles/denver00001.jpg",
		imgAlt: "Denver, the Last Dinosaur - Pins",
		color: "white",
		category: "Pins",
		medium: 2,
		price: "11,90 €",
		description: "A colorfull pins of Denver eye-winking face.",
		url: "",
		details: {
			"Size": "33cm",
			"Weight": "33g",
		},
		gallery: [
			{ alt: "Stranger Things", src: "/images/covers/stranger-things.jpg" },
			{ alt: "Stranger Things", src: "/images/covers/stranger-things.jpg" },
			{ alt: "Stranger Things", src: "/images/covers/stranger-things.jpg" },
			{ alt: "Stranger Things", src: "/images/covers/stranger-things.jpg" },
		],
	},
	{
		id: 7,
		title: "Pins Denver",
		imgSrc: "/images/articles/denver00001.jpg",
		imgAlt: "Denver, the Last Dinosaur - Pins",
		color: "white",
		category: "Pins",
		medium: 2,
		price: "11,90 €",
		description: "A colorfull pins of Denver eye-winking face.",
		url: "",
		details: {
			"Size": "33cm",
			"Weight": "33g",
		},
		gallery: [
			{ alt: "Stranger Things", src: "/images/covers/stranger-things.jpg" },
			{ alt: "Stranger Things", src: "/images/covers/stranger-things.jpg" },
			{ alt: "Stranger Things", src: "/images/covers/stranger-things.jpg" },
			{ alt: "Stranger Things", src: "/images/covers/stranger-things.jpg" },
		],
	},
];

export default items;
